# Generated by Django 2.2 on 2019-04-20 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=None, verbose_name='date published')),
                ('text', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slackapp.Channel')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.Profile')),
            ],
        ),
    ]
