# Generated by Django 2.2 on 2019-04-20 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.Profile'),
        ),
    ]
