# Generated by Django 2.2 on 2019-04-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slackapp', '0002_auto_20190421_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
    ]
