# Generated by Django 2.2 on 2019-04-21 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_remove_profile_channel'),
        ('slackapp', '0003_auto_20190421_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='profileapp.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='profileapp.Profile'),
            preserve_default=False,
        ),
    ]
