# Generated by Django 2.2 on 2019-04-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_remove_profile_channel'),
        ('slackapp', '0004_auto_20190421_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='profile',
        ),
        migrations.AddField(
            model_name='channel',
            name='profile',
            field=models.ManyToManyField(to='profileapp.Profile'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ManyToManyField(to='profileapp.Profile'),
        ),
    ]
