# Generated by Django 2.2 on 2019-04-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_remove_profile_channel'),
        ('slackapp', '0005_auto_20190421_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='profileapp.Profile'),
            preserve_default=False,
        ),
    ]
