# Generated by Django 2.2 on 2019-04-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_profile_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='channel',
        ),
    ]
